![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [1]:
import pandas as pd
import numpy as np

# Load the dataset
schools = pd.read_csv("schools.csv")

# Calculate the percentage of the math score for each school
# This is done by dividing the average math score by the maximum score (800) and then multiplying by 100
schools["percentage_math"] = (schools["average_math"] / 800) * 100

# Filter schools with a math percentage greater than or equal to 80%
# Then, sort these schools by their average math score in descending order
best_math_schools = schools[schools["percentage_math"] >= 80][["school_name", "average_math"]].sort_values("average_math", ascending=False)

# Calculate the total SAT score for each school
# This is the sum of the average scores for math, reading, and writing
schools["total_SAT"] = schools[["average_math", "average_reading", "average_writing"]].sum(axis=1)

# Select the top 10 schools with the highest total SAT scores
# These are sorted in descending order to get the schools with the highest scores at the top
top_10_schools = schools[["school_name", "total_SAT"]].sort_values("total_SAT", ascending=False).head(10)

# Group the data by borough
# For each borough, calculate the standard deviation, mean, and count of total SAT scores
std_per_borough = schools.groupby("borough")["total_SAT"].agg(['std', 'mean', 'count']).reset_index()

# Identify the borough with the highest standard deviation in SAT scores
# This indicates the borough with the largest spread in SAT scores
max_std_borough = std_per_borough[std_per_borough['std'] == std_per_borough['std'].max()]

# Rename the columns for clarity and round the numerical values to two decimal places
# This makes the data more readable and understandable
largest_std_dev = max_std_borough.rename(columns={'std': 'std_SAT', 'mean': 'average_SAT', 'count': 'num_schools'}).round(2)

# Display the borough with the largest standard deviation in SAT scores
largest_std_dev

     borough  std_SAT  average_SAT  num_schools
2  Manhattan   230.29      1340.13           89